api_list: []
use_api: 0
translate:
  appid: ""
  appkey: ""
nsfw_check:
  enable: false
  appid: ""
  apikey: ""
def_param:
  negative_prompt: EasyNegativeV2
  height: 768
  denoising_strength: 0.55
  enable_hr: true
  hr_scale: 1.5
  hr_upscaler: R-ESRGAN 4x+ Anime6B